name: TaskRun
version: 1.0
main: com.brandonjja.taskRun.TaskRun
author: Brandonjja
description: TaskRun
commands:
    newgame:
        usage: /newgame
        description: Starts a new game
    tasks:
        usage: /tasks
        description: Displays a list of tasks to do
    toggletasks:
        usage: /toggletasks
        description: Toggles the side task bar
    tt:
        usage: /tt
        description: Toggles the side task bar (same as /toggletasks)